version: '3.9'
services:
    app:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/app
        command: npm run start

networks:
    my-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.238.0/24
